version: '3.8'

services:
  optiomax_runner:
    image: $APP_IMAGE_NAME:$VERSION
    container_name: $APP_CONTAINER_NAME
    env_file:
      - ./envs/app.env
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.5'
        reservations:
          memory: 1G
          cpus: '0.5'
      restart_policy:
        condition: unless-stopped
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ["CMD", "php", "/var/www/html/artisan", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    volumes:
      - app_storage:/var/www/html/storage
      - app_logs:/var/www/html/storage/logs
    networks:
      - optiomax_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    depends_on:
      optiomax_runner:
        condition: service_healthy
    image: $PROXY_IMAGE_NAME:$VERSION
    container_name: $PROXY_CONTAINER_NAME
    ports:
      - "$APP_PROXY_PORT:80"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
      restart_policy:
        condition: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - optiomax_network
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

volumes:
  app_storage:
    driver: local
  app_logs:
    driver: local

networks:
  optiomax_network:
    driver: bridge