<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class DocumentCategoryFieldSeeder extends Seeder
{  
    /**
     * Run the database seeds.
     */
    public function run(): void
    { 
        if (!Schema::hasTable('document_category_field')) {
            return;
        }

        $now = Carbon::now();

        $rows = [
            // 1
            [
                'id' => 1,
                'document_category_id'=>8,
                'document_field_name'=>"Br attachment",
                'description'=>"BR attachment (supplier registration)",
                'file_path'=>'uploads/supplier/br_attachment',
                'isactive'=>true,
                'document_formats'=>'PDF,DOC,DOCX,JPG,PNG,JPEG',
                'max_upload_count'=>5,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 2
            [
                'id' => 2,
                'document_category_id'=>16,
                'document_field_name'=>"Item master image",
                'description'=>"Item master image (catalog photo)",
                'file_path'=>'uploads/items/item_images',
                'isactive'=>true,
                'document_formats'=>'PDF,DOC,DOCX,JPG,PNG,JPEG',
                'max_upload_count'=>5,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 3
            [
                'id' => 3,
                'document_category_id'=>11,
                'document_field_name'=>"User Profile image",
                'description'=>"Profile image (user avatar)",
                'file_path'=>'uploads/profile_image',
                'isactive'=>true,
                'document_formats'=>'SVG,PNG,JPG,GIF',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>false,
            ],
            // 4
            [
                'id' => 4,
                'document_category_id'=>4,
                'document_field_name'=>"any document related with asset",
                'description'=>"Asset documents (related files)",
                'file_path'=>'uploads/AssestRequisition/Assest',
                'isactive'=>true,
                'document_formats'=>'SVG,PNG,JPG,GIF,DOC,DOCX,CSV,PDF',
                'max_upload_count'=>5,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 5
            [
                'id' => 5,
                'document_category_id'=>2,
                'document_field_name'=>"Thumbnail images",
                'description'=>"Asset group thumbnail (preview image)",
                'file_path'=>'uploads/assets/thumbnail_image',
                'isactive'=>true,
                'document_formats'=>'SVG,PNG,JPG,GIF,DOC,DOCX,CSV,PDF',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>false,
            ],
            // 6
            [
                'id' => 6,
                'document_category_id'=>3,
                'document_field_name'=>"Thumbnail images",
                'description'=>"Asset item thumbnail (preview image)",
                'file_path'=>'uploads/assets/thumbnail_image',
                'isactive'=>true,
                'document_formats'=>'SVG,PNG,JPG,GIF,DOC,DOCX,CSV,PDF',
                'max_upload_count'=>5,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>false,
            ],
            // 7
            [
                'id' => 7,
                'document_category_id'=>3,
                'document_field_name'=>"Purchase documents",
                'description'=>"Purchase documents (invoice/receipt/PO)",
                'file_path'=>'uploads/assets/purchase_document',
                'isactive'=>true,
                'document_formats'=>'SVG,PNG,JPG,GIF,DOC,DOCX,CSV,PDF',
                'max_upload_count'=>5,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 8
            [
                'id' => 8,
                'document_category_id'=>3,
                'document_field_name'=>"item documents",
                'description'=>"Item documents (manual/specs)",
                'file_path'=>'uploads/assets/assets_document',
                'isactive'=>true,
                'document_formats'=>'SVG,PNG,JPG,GIF,DOC,DOCX,CSV,PDF',
                'max_upload_count'=>5,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 9
            [
                'id' => 9,
                'document_category_id'=>3,
                'document_field_name'=>"insurance documents",
                'description'=>"Insurance documents (policy/cert)",
                'file_path'=>'uploads/assets/insurance_document',
                'isactive'=>true,
                'document_formats'=>'SVG,PNG,JPG,GIF,DOC,DOCX,CSV,PDF',
                'max_upload_count'=>5,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 10
            [
                'id' => 10,
                'document_category_id'=>14,
                'document_field_name'=>"permit documents",
                'description'=>"Permit documents (work permits)",
                'file_path'=>'uploads/work_orders/permit_documents',
                'isactive'=>true,
                'document_formats'=>'SVG,PNG,JPG,GIF,DOC,DOCX,CSV,PDF',
                'max_upload_count'=>5,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 11
            [
                'id' => 11,
                'document_category_id'=>5,
                'document_field_name'=>"upload files",
                'description'=>"Procurement files (attachments)",
                'file_path'=>'uploads/Procurement/attachment',
                'isactive'=>true,
                'document_formats'=>'SVG,PNG,JPG,GIF,DOC,DOCX,CSV,PDF',
                'max_upload_count'=>5,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 12
            [
                'id' => 12,
                'document_category_id'=>5,
                'document_field_name'=>"RPF documents",
                'description'=>"RPF documents (tender files)",
                'file_path'=>'uploads/Procurement/rpf_document',
                'isactive'=>true,
                'document_formats'=>'SVG,PNG,JPG,GIF,DOC,DOCX,CSV,PDF',
                'max_upload_count'=>5,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 13
            [
                'id' => 13,
                'document_category_id'=>15,
                'document_field_name'=>"Work order completion image",
                'description'=>"Completion image (work order)",
                'file_path'=>'uploads/work_orders/completion_images',
                'isactive'=>true,
                'document_formats'=>'SVG,PNG,JPG,GIF,DOC,DOCX,CSV,PDF',
                'max_upload_count'=>5,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 14
            [
                'id' => 14,
                'document_category_id'=>17,
                'document_field_name'=>"Incident reports Attachments",
                'description'=>"Incident attachments (report files)",
                'file_path'=>'uploads/incident_reports/attachments',
                'isactive'=>true,
                'document_formats'=>'SVG,PNG,JPG,GIF,DOC,DOCX,CSV,PDF',
                'max_upload_count'=>5,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 15
            [
                'id' => 15,
                'document_category_id'=>9,
                'document_field_name'=>"Supplier Quotation Attachments",
                'description'=>"Quotation attachments (supplier quote)",
                'file_path'=>'uploads/supplier_quotation/attachments',
                'isactive'=>true,
                'document_formats'=>'SVG,PNG,JPG,GIF,DOC,DOCX,CSV,PDF',
                'max_upload_count'=>5,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 16
            [
                'id' => 16,
                'document_category_id'=>19,
                'document_field_name'=>"Asset Availability Attachments",
                'description'=>"Availability attachments (supporting files)",
                'file_path'=>'uploads/asset_availability/attachments',
                'isactive'=>true,
                'document_formats'=>'SVG,PNG,JPG,GIF,DOC,DOCX,CSV,PDF',
                'max_upload_count'=>5,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 17
            [
                'id' => 17,
                'document_category_id'=>20,
                'document_field_name'=>"National ID card",
                'description'=>"National ID (identity proof)",
                'file_path'=>'uploads/asset_booking/identity/national_id',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 18
            [
                'id' => 18,
                'document_category_id'=>20,
                'document_field_name'=>"Passport",
                'description'=>"Passport (identity proof)",
                'file_path'=>'uploads/asset_booking/identity/passport',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 19
            [
                'id' => 19,
                'document_category_id'=>20,
                'document_field_name'=>"Driver’s license",
                'description'=>"Driver's license (identity proof)",
                'file_path'=>'uploads/asset_booking/identity/drivers_license',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 20
            [
                'id' => 20,
                'document_category_id'=>20,
                'document_field_name'=>"Employee ID card",
                'description'=>"Employee ID (employment proof)",
                'file_path'=>'uploads/asset_booking/employment/employee_id',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 21
            [
                'id' => 21,
                'document_category_id'=>20,
                'document_field_name'=>"Company authorization letter",
                'description'=>"Authorization letter (company access)",
                'file_path'=>'uploads/asset_booking/employment/authorization_letter',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG,DOC,DOCX',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 22
            [
                'id' => 22,
                'document_category_id'=>20,
                'document_field_name'=>"Student ID",
                'description'=>"Student ID (education proof)",
                'file_path'=>'uploads/asset_booking/employment/student_id',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 23
            [
                'id' => 23,
                'document_category_id'=>20,
                'document_field_name'=>"Utility bill",
                'description'=>"Utility bill (address proof)",
                'file_path'=>'uploads/asset_booking/address/utility_bill',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 24
            [
                'id' => 24,
                'document_category_id'=>20,
                'document_field_name'=>"Bank statement",
                'description'=>"Bank statement (address proof)",
                'file_path'=>'uploads/asset_booking/address/bank_statement',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 25
            [
                'id' => 25,
                'document_category_id'=>20,
                'document_field_name'=>"Official correspondence",
                'description'=>"Official letter (address proof)",
                'file_path'=>'uploads/asset_booking/address/official_correspondence',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 26
            [
                'id' => 26,
                'document_category_id'=>20,
                'document_field_name'=>"Equipment operation license",
                'description'=>"Operation license (equipment use)",
                'file_path'=>'uploads/asset_booking/licenses/equipment_operation',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 27
            [
                'id' => 27,
                'document_category_id'=>20,
                'document_field_name'=>"Access permit",
                'description'=>"Access permit (restricted use)",
                'file_path'=>'uploads/asset_booking/licenses/access_permit',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 28
            [
                'id' => 28,
                'document_category_id'=>20,
                'document_field_name'=>"Forklift/heavy machinery operator license",
                'description'=>"Forklift license (operator proof)",
                'file_path'=>'uploads/asset_booking/licenses/forklift_operator',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 29
            [
                'id' => 29,
                'document_category_id'=>20,
                'document_field_name'=>"Supervisor approval",
                'description'=>"Supervisor approval (manager signoff)",
                'file_path'=>'uploads/asset_booking/authorization/supervisor_approval',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG,DOC,DOCX',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 30
            [
                'id' => 30,
                'document_category_id'=>20,
                'document_field_name'=>"Department head approval",
                'description'=>"Department head approval (signoff)",
                'file_path'=>'uploads/asset_booking/authorization/department_head_approval',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG,DOC,DOCX',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 31
            [
                'id' => 31,
                'document_category_id'=>20,
                'document_field_name'=>"Project manager approval",
                'description'=>"Project manager approval (signoff)",
                'file_path'=>'uploads/asset_booking/authorization/project_manager_approval',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG,DOC,DOCX',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 32
            [
                'id' => 32,
                'document_category_id'=>20,
                'document_field_name'=>"Insurance certificate",
                'description'=>"Insurance certificate (coverage proof)",
                'file_path'=>'uploads/asset_booking/insurance/certificate',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 33
            [
                'id' => 33,
                'document_category_id'=>20,
                'document_field_name'=>"Temporary insurance",
                'description'=>"Temporary insurance (coverage proof)",
                'file_path'=>'uploads/asset_booking/insurance/temporary',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 34
            [
                'id' => 34,
                'document_category_id'=>20,
                'document_field_name'=>"Liability waiver",
                'description'=>"Liability waiver (signed form)",
                'file_path'=>'uploads/asset_booking/insurance/liability_waiver',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG,DOC,DOCX',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 35
            [
                'id' => 35,
                'document_category_id'=>20,
                'document_field_name'=>"Credit/debit card details",
                'description'=>"Card details (payment proof)",
                'file_path'=>'uploads/asset_booking/payment/card_details',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 36
            [
                'id' => 36,
                'document_category_id'=>20,
                'document_field_name'=>"Purchase order",
                'description'=>"Purchase order (corporate booking)",
                'file_path'=>'uploads/asset_booking/payment/purchase_order',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG,DOC,DOCX',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 37
            [
                'id' => 37,
                'document_category_id'=>20,
                'document_field_name'=>"Bank transfer/deposit slip",
                'description'=>"Bank transfer slip (payment proof)",
                'file_path'=>'uploads/asset_booking/payment/bank_transfer',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 38
            [
                'id' => 38,
                'document_category_id'=>20,
                'document_field_name'=>"Internal cost center code",
                'description'=>"Cost center code (internal billing)",
                'file_path'=>'uploads/asset_booking/payment/cost_center_code',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG,DOC,DOCX',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 39
            [
                'id' => 39,
                'document_category_id'=>20,
                'document_field_name'=>"Safety training certificate",
                'description'=>"Safety certificate (training proof)",
                'file_path'=>'uploads/asset_booking/special/safety_training',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 40
            [
                'id' => 40,
                'document_category_id'=>20,
                'document_field_name'=>"Event permit",
                'description'=>"Event permit (usage approval)",
                'file_path'=>'uploads/asset_booking/special/event_permit',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 41
            [
                'id' => 41,
                'document_category_id'=>20,
                'document_field_name'=>"Health certificate",
                'description'=>"Health certificate (compliance proof)",
                'file_path'=>'uploads/asset_booking/special/health_certificate',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 42
            [
                'id' => 42,
                'document_category_id'=>20,
                'document_field_name'=>"Customs clearance documents",
                'description'=>"Customs clearance (import docs)",
                'file_path'=>'uploads/asset_booking/special/customs_clearance',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 43
            [
                'id' => 43,
                'document_category_id'=>20,
                'document_field_name'=>"Environmental clearance",
                'description'=>"Environmental clearance (permit docs)",
                'file_path'=>'uploads/asset_booking/special/environmental_clearance',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 44
            [
                'id' => 44,
                'document_category_id'=>20,
                'document_field_name'=>"Equipment calibration certificate",
                'description'=>"Calibration certificate (equipment proof)",
                'file_path'=>'uploads/asset_booking/special/calibration_certificate',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 45
            [
                'id' => 45,
                'document_category_id'=>20,
                'document_field_name'=>"Signed rental agreement",
                'description'=>"Rental agreement (signed terms)",
                'file_path'=>'uploads/asset_booking/terms/rental_agreement',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG,DOC,DOCX',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 46
            [
                'id' => 46,
                'document_category_id'=>20,
                'document_field_name'=>"Digital acceptance of terms",
                'description'=>"Digital acceptance (terms consent)",
                'file_path'=>'uploads/asset_booking/terms/digital_acceptance',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 47
            [
                'id' => 47,
                'document_category_id'=>20,
                'document_field_name'=>"Non-disclosure agreement",
                'description'=>"NDA (confidentiality terms)",
                'file_path'=>'uploads/asset_booking/terms/nda',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG,DOC,DOCX',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 48
            [
                'id' => 48,
                'document_category_id'=>20,
                'document_field_name'=>"Asset check-out form",
                'description'=>"Check-out form (handover record)",
                'file_path'=>'uploads/asset_booking/handover/checkout_form',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG,DOC,DOCX',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 49
            [
                'id' => 49,
                'document_category_id'=>20,
                'document_field_name'=>"Asset check-in form",
                'description'=>"Check-in form (return record)",
                'file_path'=>'uploads/asset_booking/handover/checkin_form',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG,DOC,DOCX',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 50
            [
                'id' => 50,
                'document_category_id'=>20,
                'document_field_name'=>"Condition report",
                'description'=>"Condition report (before/after)",
                'file_path'=>'uploads/asset_booking/handover/condition_report',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG,DOC,DOCX',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 51
            [
                'id' => 51,
                'document_category_id'=>20,
                'document_field_name'=>"Photo evidence of asset condition",
                'description'=>"Condition photos (before/after)",
                'file_path'=>'uploads/asset_booking/handover/photo_evidence',
                'isactive'=>true,
                'document_formats'=>'JPG,PNG',
                'max_upload_count'=>5,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 52
            [
                'id' => 52,
                'document_category_id'=>20,
                'document_field_name'=>"Project proposal",
                'description'=>"Project proposal (justification)",
                'file_path'=>'uploads/asset_booking/supporting/project_proposal',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG,DOC,DOCX',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 53
            [
                'id' => 53,
                'document_category_id'=>20,
                'document_field_name'=>"Budget approval document",
                'description'=>"Budget approval (approval doc)",
                'file_path'=>'uploads/asset_booking/supporting/budget_approval',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG,DOC,DOCX',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 54
            [
                'id' => 54,
                'document_category_id'=>20,
                'document_field_name'=>"Reference/endorsement letter",
                'description'=>"Reference letter (endorsement)",
                'file_path'=>'uploads/asset_booking/supporting/reference_letter',
                'isactive'=>true,
                'document_formats'=>'PDF,JPG,PNG,DOC,DOCX',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 55
            [
                'id' => 55,
                'document_category_id'=>18,
                'document_field_name'=>"Customer Attachments",
                'description'=>"Customer attachments (supporting files)",
                'file_path'=>'uploads/customer_attachments',
                'isactive'=>true,
                'document_formats'=>'SVG,PNG,JPG,GIF,DOC,DOCX,CSV,PDF',
                'max_upload_count'=>5,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 56
             [
                'id' => 56,
                'document_category_id'=>18,
                'document_field_name'=>"Customer logo/image",
                     'description'=>"Customer logo (brand image)",
                'file_path'=>'uploads/customer_thumbnail_image',
                'isactive'=>true,
                'document_formats'=>'SVG,PNG,JPG,JPEG',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>false,
            ],
            // 57
            [
                'id' => 57,
                'document_category_id'=>21,
                'document_field_name'=>"Upload bulk data files",
                'description'=>"Bulk upload (asset master)",
                'file_path'=>'uploads/bulk_data_import/asset_master',
                'isactive'=>true,
                'document_formats'=>'CSV,XLSX,XLS',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 58
            [ 
                'id' => 58,
                'document_category_id'=>22,
                'document_field_name'=>"Upload bulk data files",
                'description'=>"Bulk upload (supplier data)",
                'file_path'=>'uploads/bulk_data_import/supplier',
                'isactive'=>true,
                'document_formats'=>'CSV,XLSX,XLS',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ], 
            // 59
            [ 
                'id' => 59,
                'document_category_id'=>23,
                'document_field_name'=>"Upload bulk data files",
                'description'=>"Bulk upload (customer data)",
                'file_path'=>'uploads/bulk_data_import/customer',
                'isactive'=>true,
                'document_formats'=>'CSV,XLSX,XLS',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 60
            [ 
                'id' => 60,
                'document_category_id'=>24,
                'document_field_name'=>"Upload bulk data files",
                'description'=>"Bulk upload (asset category)",
                'file_path'=>'uploads/bulk_data_import/asset_category',
                'isactive'=>true,
                'document_formats'=>'CSV,XLSX,XLS',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 61
            [ 
                'id' => 61,
                'document_category_id'=>25,
                'document_field_name'=>"Upload bulk data files",
                'description'=>"Bulk upload (asset subcategory)",
                'file_path'=>'uploads/bulk_data_import/asset_sub_category',
                'isactive'=>true,
                'document_formats'=>'CSV,XLSX,XLS',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 62
            [ 
                'id' => 62,
                'document_category_id'=>26,
                'document_field_name'=>"Upload bulk data files",
                'description'=>"Bulk upload (asset group)",
                'file_path'=>'uploads/bulk_data_import/asset_group',
                'isactive'=>true,
                'document_formats'=>'CSV,XLSX,XLS',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 63
            [ 
                'id' => 63,
                'document_category_id'=>27,
                'document_field_name'=>"Upload bulk data files",
                'description'=>"Bulk upload (items master)",
                'file_path'=>'uploads/bulk_data_import/items_master',
                'isactive'=>true,
                'document_formats'=>'CSV,XLSX,XLS',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 64
            [ 
                'id' => 64,
                'document_category_id'=>28,
                'document_field_name'=>"Upload bulk data files",
                'description'=>"Bulk upload (availability terms)",
                'file_path'=>'uploads/bulk_data_import/assets_availability_terms_type',
                'isactive'=>true,
                'document_formats'=>'CSV,XLSX,XLS',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
            // 65
            [
                'id'=>65,
                'document_category_id'=>3,
                'document_field_name'=>"QR code image",
                'description'=>"asset QR code image",
                'file_path'=>'uploads/assets/qr_code_image',
                'isactive'=>true,
                'document_formats'=>'SVG,PNG,JPG,GIF,DOC,DOCX,CSV,PDF',
                'max_upload_count'=>1,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>false,

            ],
            // 66
            [
                'id' => 66,
                'document_category_id'=>29,
                'document_field_name'=>"Any document related with asset",
                'description'=>"Asset documents (related files)",
                'file_path'=>'uploads/MyInternalAssetsRequisitions/AssetDocument',
                'isactive'=>true,
                'document_formats'=>'SVG,PNG,JPG,GIF,DOC,DOCX,CSV,PDF',
                'max_upload_count'=>5,
                'created_at' => $now,
                'updated_at' => $now,
                'listable'=>true,
            ],
        ];
 
        DB::table('document_category_field')->upsert(
            $rows,
            ['id'],
            [
                'document_category_id',
                'document_field_name',
                'description',
                'file_path',
                'isactive',
                'document_formats',
                'max_upload_count',
                'updated_at',
                'listable',
            ]
        );
    }
}
