<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PackageDiscountsSeeder extends Seeder
{
    public function run(): void
    {
        $currentTime = Carbon::now();

        DB::table('package_discounts')->insert([
            [
                'name' => 'Welcome New Customer',
                'code' => 'WELCOME25',
                'description' => '25% discount for new customers on their first subscription',
                'type' => 'percentage',
                'value' => 25.00,
                'applicable_package_slugs' => null, // All packages
                'excluded_package_slugs' => json_encode(['free-plan']),
                'applicable_package_types' => json_encode(['INDIVIDUAL', 'ENTERPRISE']),
                'applicable_regions' => null,
                'applicable_billing_cycles' => 'both',
                'apply_to_addons' => false,
                'apply_to_setup_fees' => true,
                'first_payment_only' => true,
                'is_first_time_only' => true,
                'requires_existing_subscription' => false,
                'customer_segments' => json_encode(['new_customer', 'trial_user']),
                'usage_limit' => 1000,
                'usage_count' => 0,
                'usage_limit_per_customer' => 1,
                'minimum_amount' => 20.00,
                'maximum_discount_amount' => 100.00,
                'valid_from' => $currentTime,
                'valid_until' => $currentTime->copy()->addMonths(6),
                'valid_days_of_week' => null,
                'valid_hours' => null,
                'is_stackable' => false,
                'stackable_with' => null,
                'incompatible_with' => null,
                'compliance_requirements' => json_encode(['GDPR', 'CCPA']),
                'terms_conditions' => 'Valid for new customers only. Cannot be combined with other offers.',
                'legal_version' => '1.0',
                'stripe_coupon_id' => 'coupon_welcome25',
                'campaign_id' => 'new_customer_2024',
                'source' => 'website_signup',
                'metadata' => null,
                'isactive' => true,
                'is_public' => true,
                'requires_approval' => false,
                'approval_status' => 'approved',
                'created_by' => null,
                'updated_by' => null,
                'approved_by' => null,
                'created_at' => $currentTime,
                'updated_at' => $currentTime
            ],
            [
                'name' => 'Annual Plan Super Saver',
                'code' => 'ANNUAL20',
                'description' => 'Additional 20% off on yearly plans (on top of existing yearly discount)',
                'type' => 'percentage',
                'value' => 20.00,
                'applicable_package_slugs' => json_encode(['starter-plan', 'professional-plan', 'enterprise-plan']),
                'excluded_package_slugs' => json_encode(['free-plan']),
                'applicable_package_types' => json_encode(['INDIVIDUAL', 'ENTERPRISE']),
                'applicable_regions' => null,
                'applicable_billing_cycles' => 'yearly',
                'apply_to_addons' => true,
                'apply_to_setup_fees' => false,
                'first_payment_only' => false, // Applies to recurring payments
                'is_first_time_only' => false,
                'requires_existing_subscription' => false,
                'customer_segments' => null,
                'usage_limit' => null,
                'usage_count' => 0,
                'usage_limit_per_customer' => 2, // Can use twice (new + renewal)
                'minimum_amount' => 100.00,
                'maximum_discount_amount' => 500.00,
                'valid_from' => $currentTime,
                'valid_until' => $currentTime->copy()->addYear(),
                'valid_days_of_week' => null,
                'valid_hours' => null,
                'is_stackable' => true,
                'stackable_with' => json_encode(['UPGRADE10']),
                'incompatible_with' => null,
                'compliance_requirements' => json_encode(['GDPR', 'CCPA']),
                'terms_conditions' => 'Valid for yearly subscriptions only. Can be combined with upgrade discounts.',
                'legal_version' => '1.0',
                'stripe_coupon_id' => 'coupon_annual20',
                'campaign_id' => 'annual_promotion_2024',
                'source' => 'email_campaign',
                'metadata' => null,
                'isactive' => true,
                'is_public' => true,
                'requires_approval' => false,
                'approval_status' => 'approved',
                'created_by' => null,
                'updated_by' => null,
                'approved_by' => null,
                'created_at' => $currentTime,
                'updated_at' => $currentTime
            ],
            [
                'name' => 'Enterprise Starter Bonus',
                'code' => 'ENTERPRISE100',
                'description' => '$100 off enterprise plans + setup fee waiver',
                'type' => 'fixed_amount',
                'value' => 100.00,
                'applicable_package_slugs' => json_encode(['enterprise-plan']),
                'excluded_package_slugs' => null,
                'applicable_package_types' => json_encode(['ENTERPRISE']),
                'applicable_regions' => null,
                'applicable_billing_cycles' => 'both',
                'apply_to_addons' => false,
                'apply_to_setup_fees' => true,
                'first_payment_only' => true,
                'is_first_time_only' => true,
                'requires_existing_subscription' => false,
                'customer_segments' => json_encode(['enterprise', 'large_team']),
                'usage_limit' => 50,
                'usage_count' => 0,
                'usage_limit_per_customer' => 1,
                'minimum_amount' => 299.00,
                'maximum_discount_amount' => 1100.00, // $100 + $1000 setup fee
                'valid_from' => $currentTime,
                'valid_until' => $currentTime->copy()->addMonths(3),
                'valid_days_of_week' => null,
                'valid_hours' => null,
                'is_stackable' => false,
                'stackable_with' => null,
                'incompatible_with' => null,
                'compliance_requirements' => json_encode(['GDPR', 'SOC2', 'ISO27001']),
                'terms_conditions' => 'Valid for new enterprise customers only. Includes setup fee waiver.',
                'legal_version' => '1.0',
                'stripe_coupon_id' => 'coupon_enterprise100',
                'campaign_id' => 'enterprise_launch_2024',
                'source' => 'sales_team',
                'metadata' => null,
                'isactive' => true,
                'is_public' => false, // Sales team only
                'requires_approval' => true,
                'approval_status' => 'approved',
                'created_by' => null,
                'updated_by' => null,
                'approved_by' => null,
                'created_at' => $currentTime,
                'updated_at' => $currentTime
            ],
            [
                'name' => 'Student & Educator Discount',
                'code' => 'STUDENT50',
                'description' => '50% off for students and educational institutions',
                'type' => 'percentage',
                'value' => 50.00,
                'applicable_package_slugs' => json_encode(['starter-plan', 'professional-plan']),
                'excluded_package_slugs' => json_encode(['free-plan', 'enterprise-plan']),
                'applicable_package_types' => json_encode(['INDIVIDUAL']),
                'applicable_regions' => null,
                'applicable_billing_cycles' => 'both',
                'apply_to_addons' => true,
                'apply_to_setup_fees' => true,
                'first_payment_only' => false, // Ongoing discount
                'is_first_time_only' => false,
                'requires_existing_subscription' => false,
                'customer_segments' => json_encode(['student', 'educator', 'academic']),
                'usage_limit' => null,
                'usage_count' => 0,
                'usage_limit_per_customer' => 1,
                'minimum_amount' => 10.00,
                'maximum_discount_amount' => null, // No cap for students
                'valid_from' => $currentTime,
                'valid_until' => null, // No expiry
                'valid_days_of_week' => null,
                'valid_hours' => null,
                'is_stackable' => false,
                'stackable_with' => null,
                'incompatible_with' => null,
                'compliance_requirements' => json_encode(['GDPR', 'CCPA', 'FERPA']),
                'terms_conditions' => 'Valid student/educator ID required. Subject to verification.',
                'legal_version' => '1.0',
                'stripe_coupon_id' => 'coupon_student50',
                'campaign_id' => 'education_program_2024',
                'source' => 'education_portal',
                'metadata' => null,
                'isactive' => true,
                'is_public' => true,
                'requires_approval' => true, // Requires verification
                'approval_status' => 'approved',
                'created_by' => null,
                'updated_by' => null,
                'approved_by' => null,
                'created_at' => $currentTime,
                'updated_at' => $currentTime
            ],
            [
                'name' => 'Upgrade Incentive',
                'code' => 'UPGRADE10',
                'description' => '10% off when upgrading from a lower tier plan',
                'type' => 'percentage',
                'value' => 10.00,
                'applicable_package_slugs' => json_encode(['professional-plan', 'enterprise-plan']),
                'excluded_package_slugs' => null,
                'applicable_package_types' => json_encode(['INDIVIDUAL', 'ENTERPRISE']),
                'applicable_regions' => null,
                'applicable_billing_cycles' => 'both',
                'apply_to_addons' => false,
                'apply_to_setup_fees' => false,
                'first_payment_only' => true,
                'is_first_time_only' => false,
                'requires_existing_subscription' => true, // Must have existing subscription
                'customer_segments' => json_encode(['existing_customer', 'upgrade_candidate']),
                'usage_limit' => null,
                'usage_count' => 0,
                'usage_limit_per_customer' => 3, // Can upgrade multiple times
                'minimum_amount' => 50.00,
                'maximum_discount_amount' => 200.00,
                'valid_from' => $currentTime,
                'valid_until' => null,
                'valid_days_of_week' => null,
                'valid_hours' => null,
                'is_stackable' => true,
                'stackable_with' => json_encode(['ANNUAL20']),
                'incompatible_with' => null,
                'compliance_requirements' => json_encode(['GDPR', 'CCPA']),
                'terms_conditions' => 'Valid for existing customers upgrading to higher tier plans.',
                'legal_version' => '1.0',
                'stripe_coupon_id' => 'coupon_upgrade10',
                'campaign_id' => 'upgrade_incentive_2024',
                'source' => 'upgrade_flow',
                'metadata' => null,
                'isactive' => true,
                'is_public' => false, // Only shown during upgrade flow
                'requires_approval' => false,
                'approval_status' => 'approved',
                'created_by' => null,
                'updated_by' => null,
                'approved_by' => null,
                'created_at' => $currentTime,
                'updated_at' => $currentTime
            ]
        ]);
    }
}
