<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PackageAddonsSeeder extends Seeder
{
    public function run(): void
    {
        $currentTime = Carbon::now();

        DB::table('package_addons')->insert([
            [
                'name' => 'Extra Credits Bundle',
                'slug' => 'extra-credits-bundle',
                'description' => 'Add 1000 additional credits to your monthly allowance',
                'addon_type' => 'limit_increase',
                'target_feature' => 'credits',
                'price_monthly' => 15.00,
                'price_yearly' => 150.00,
                'boost_values' => json_encode([
                    'credits' => 1000,
                    'rollover_allowed' => false
                ]),
                'applicable_package_slugs' => json_encode(['starter-plan', 'professional-plan']),
                'excluded_package_slugs' => json_encode(['free-plan', 'enterprise-plan']),
                'applicable_package_types' => json_encode(['INDIVIDUAL', 'ENTERPRISE']),
                'regional_restrictions' => null,
                'is_stackable' => true,
                'max_quantity' => 10,
                'min_quantity' => 1,
                'requires_approval' => false,
                'auto_scale' => false,
                'is_metered' => false,
                'metered_rate' => 0.0000,
                'metered_unit' => null,
                'prorated_billing' => true,
                'compliance_requirements' => json_encode(['GDPR', 'CCPA']),
                'terms_conditions' => 'Credits are valid for the billing period only. No rollover to next period.',
                'legal_version' => '1.0',
                'stripe_price_id_monthly' => 'price_addon_credits_monthly',
                'stripe_price_id_yearly' => 'price_addon_credits_yearly',
                'stripe_product_id' => 'prod_addon_credits',
                'stripe_meter_id' => null,
                'isactive' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'available_from' => $currentTime,
                'available_until' => null,
                'created_by' => null,
                'updated_by' => null,
                'created_at' => $currentTime,
                'updated_at' => $currentTime
            ],
            [
                'name' => 'Team Expansion Pack',
                'slug' => 'team-expansion-pack',
                'description' => 'Add 10 additional team members to your workspace',
                'addon_type' => 'limit_increase',
                'target_feature' => 'users',
                'price_monthly' => 50.00,
                'price_yearly' => 500.00,
                'boost_values' => json_encode([
                    'users' => 10,
                    'includes_admin_controls' => true,
                    'includes_role_management' => true
                ]),
                'applicable_package_slugs' => json_encode(['starter-plan', 'professional-plan']),
                'excluded_package_slugs' => json_encode(['free-plan']),
                'applicable_package_types' => json_encode(['INDIVIDUAL', 'ENTERPRISE']),
                'regional_restrictions' => null,
                'is_stackable' => true,
                'max_quantity' => 5,
                'min_quantity' => 1,
                'requires_approval' => false,
                'auto_scale' => false,
                'is_metered' => false,
                'metered_rate' => 0.0000,
                'metered_unit' => null,
                'prorated_billing' => true,
                'compliance_requirements' => json_encode(['GDPR', 'CCPA', 'SOC2']),
                'terms_conditions' => 'Additional users are subject to the same terms as base package users.',
                'legal_version' => '1.0',
                'stripe_price_id_monthly' => 'price_addon_users_monthly',
                'stripe_price_id_yearly' => 'price_addon_users_yearly',
                'stripe_product_id' => 'prod_addon_users',
                'stripe_meter_id' => null,
                'isactive' => true,
                'is_featured' => false,
                'sort_order' => 2,
                'available_from' => $currentTime,
                'available_until' => null,
                'created_by' => null,
                'updated_by' => null,
                'created_at' => $currentTime,
                'updated_at' => $currentTime
            ],
            [
                'name' => 'Premium Storage Extension',
                'slug' => 'premium-storage-extension',
                'description' => 'Add 100GB of secure cloud storage with advanced encryption',
                'addon_type' => 'limit_increase',
                'target_feature' => 'storage_gb',
                'price_monthly' => 25.00,
                'price_yearly' => 250.00,
                'boost_values' => json_encode([
                    'storage_gb' => 100,
                    'encryption_level' => 'AES-256',
                    'backup_included' => true,
                    'geo_replication' => true
                ]),
                'applicable_package_slugs' => null,
                'excluded_package_slugs' => null,
                'applicable_package_types' => json_encode(['INDIVIDUAL', 'ENTERPRISE']),
                'regional_restrictions' => null,
                'is_stackable' => true,
                'max_quantity' => 20,
                'min_quantity' => 1,
                'requires_approval' => false,
                'auto_scale' => true,
                'is_metered' => true,
                'metered_rate' => 0.5000,
                'metered_unit' => 'per_gb',
                'prorated_billing' => true,
                'compliance_requirements' => json_encode(['GDPR', 'CCPA', 'SOC2', 'ISO27001']),
                'terms_conditions' => 'Storage is subject to fair usage policy. Data retention according to base package terms.',
                'legal_version' => '1.1',
                'stripe_price_id_monthly' => 'price_addon_storage_monthly',
                'stripe_price_id_yearly' => 'price_addon_storage_yearly',
                'stripe_product_id' => 'prod_addon_storage',
                'stripe_meter_id' => 'meter_storage_overage',
                'isactive' => true,
                'is_featured' => false,
                'sort_order' => 3,
                'available_from' => $currentTime,
                'available_until' => null,
                'created_by' => null,
                'updated_by' => null,
                'created_at' => $currentTime,
                'updated_at' => $currentTime
            ],
            [
                'name' => 'Advanced Workflow Engine',
                'slug' => 'advanced-workflow-engine',
                'description' => 'Unlock advanced workflow features with AI-powered automation',
                'addon_type' => 'feature_boost',
                'target_feature' => 'workflows',
                'price_monthly' => 75.00,
                'price_yearly' => 750.00,
                'boost_values' => json_encode([
                    'additional_workflows' => 25,
                    'ai_automation' => true,
                    'advanced_triggers' => true,
                    'custom_integrations' => true,
                    'workflow_analytics' => true
                ]),
                'applicable_package_slugs' => json_encode(['professional-plan', 'enterprise-plan']),
                'excluded_package_slugs' => json_encode(['free-plan', 'starter-plan']),
                'applicable_package_types' => json_encode(['INDIVIDUAL', 'ENTERPRISE']),
                'regional_restrictions' => null,
                'is_stackable' => false,
                'max_quantity' => 1,
                'min_quantity' => 1,
                'requires_approval' => true,
                'auto_scale' => false,
                'is_metered' => false,
                'metered_rate' => 0.0000,
                'metered_unit' => null,
                'prorated_billing' => true,
                'compliance_requirements' => json_encode(['GDPR', 'CCPA', 'SOC2', 'ISO27001', 'HIPAA_READY']),
                'terms_conditions' => 'Advanced features subject to additional compliance requirements. AI features may have usage limitations.',
                'legal_version' => '2.0',
                'stripe_price_id_monthly' => 'price_addon_workflows_monthly',
                'stripe_price_id_yearly' => 'price_addon_workflows_yearly',
                'stripe_product_id' => 'prod_addon_workflows',
                'stripe_meter_id' => null,
                'isactive' => true,
                'is_featured' => true,
                'sort_order' => 4,
                'available_from' => $currentTime,
                'available_until' => null,
                'created_by' => null,
                'updated_by' => null,
                'created_at' => $currentTime,
                'updated_at' => $currentTime
            ],
            [
                'name' => 'Enterprise Support Plus',
                'slug' => 'enterprise-support-plus',
                'description' => 'Dedicated support manager with 24/7 availability and SLA guarantees',
                'addon_type' => 'service',
                'target_feature' => 'support',
                'price_monthly' => 200.00,
                'price_yearly' => 2000.00,
                'boost_values' => json_encode([
                    'dedicated_manager' => true,
                    'response_time_sla' => '1 hour',
                    'availability' => '24/7',
                    'phone_support' => true,
                    'video_support' => true,
                    'custom_onboarding' => true
                ]),
                'applicable_package_slugs' => json_encode(['professional-plan', 'enterprise-plan']),
                'excluded_package_slugs' => json_encode(['free-plan', 'starter-plan']),
                'applicable_package_types' => json_encode(['ENTERPRISE']),
                'regional_restrictions' => json_encode(['US', 'EU', 'UK', 'CA', 'AU']),
                'is_stackable' => false,
                'max_quantity' => 1,
                'min_quantity' => 1,
                'requires_approval' => true,
                'auto_scale' => false,
                'is_metered' => false,
                'metered_rate' => 0.0000,
                'metered_unit' => null,
                'prorated_billing' => true,
                'compliance_requirements' => json_encode(['GDPR', 'SOC2_TYPE2', 'ISO27001']),
                'terms_conditions' => 'Enterprise support subject to separate SLA agreement. Availability may vary by region.',
                'legal_version' => '1.0',
                'stripe_price_id_monthly' => 'price_addon_support_monthly',
                'stripe_price_id_yearly' => 'price_addon_support_yearly',
                'stripe_product_id' => 'prod_addon_support',
                'stripe_meter_id' => null,
                'isactive' => true,
                'is_featured' => false,
                'sort_order' => 5,
                'available_from' => $currentTime,
                'available_until' => null,
                'created_by' => null,
                'updated_by' => null,
                'created_at' => $currentTime,
                'updated_at' => $currentTime
            ]
        ]);
    }
}
